//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace where2go.W2GOWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppException", Namespace="http://schemas.datacontract.org/2004/07/AppLibrary")]
    [System.SerializableAttribute()]
    public partial class AppException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Reference {
            get {
                return this.ReferenceField;
            }
            set {
                if ((this.ReferenceField.Equals(value) != true)) {
                    this.ReferenceField = value;
                    this.RaisePropertyChanged("Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsersInfo", Namespace="http://schemas.datacontract.org/2004/07/UsersLibrary")]
    [System.SerializableAttribute()]
    public partial class UsersInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ptidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int countryidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string country_arField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string country_enField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imgurlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailverifyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mobilecodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mobileverifyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string created_dtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modified_dtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ptid {
            get {
                return this.ptidField;
            }
            set {
                if ((this.ptidField.Equals(value) != true)) {
                    this.ptidField = value;
                    this.RaisePropertyChanged("ptid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstnameField, value) != true)) {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastnameField, value) != true)) {
                    this.lastnameField = value;
                    this.RaisePropertyChanged("lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int countryid {
            get {
                return this.countryidField;
            }
            set {
                if ((this.countryidField.Equals(value) != true)) {
                    this.countryidField = value;
                    this.RaisePropertyChanged("countryid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string country_ar {
            get {
                return this.country_arField;
            }
            set {
                if ((object.ReferenceEquals(this.country_arField, value) != true)) {
                    this.country_arField = value;
                    this.RaisePropertyChanged("country_ar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string country_en {
            get {
                return this.country_enField;
            }
            set {
                if ((object.ReferenceEquals(this.country_enField, value) != true)) {
                    this.country_enField = value;
                    this.RaisePropertyChanged("country_en");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                if ((object.ReferenceEquals(this.mobileField, value) != true)) {
                    this.mobileField = value;
                    this.RaisePropertyChanged("mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string imgurl {
            get {
                return this.imgurlField;
            }
            set {
                if ((object.ReferenceEquals(this.imgurlField, value) != true)) {
                    this.imgurlField = value;
                    this.RaisePropertyChanged("imgurl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string emailcode {
            get {
                return this.emailcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.emailcodeField, value) != true)) {
                    this.emailcodeField = value;
                    this.RaisePropertyChanged("emailcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string emailverify {
            get {
                return this.emailverifyField;
            }
            set {
                if ((object.ReferenceEquals(this.emailverifyField, value) != true)) {
                    this.emailverifyField = value;
                    this.RaisePropertyChanged("emailverify");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string mobilecode {
            get {
                return this.mobilecodeField;
            }
            set {
                if ((object.ReferenceEquals(this.mobilecodeField, value) != true)) {
                    this.mobilecodeField = value;
                    this.RaisePropertyChanged("mobilecode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string mobileverify {
            get {
                return this.mobileverifyField;
            }
            set {
                if ((object.ReferenceEquals(this.mobileverifyField, value) != true)) {
                    this.mobileverifyField = value;
                    this.RaisePropertyChanged("mobileverify");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string created_dt {
            get {
                return this.created_dtField;
            }
            set {
                if ((object.ReferenceEquals(this.created_dtField, value) != true)) {
                    this.created_dtField = value;
                    this.RaisePropertyChanged("created_dt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string modified_dt {
            get {
                return this.modified_dtField;
            }
            set {
                if ((object.ReferenceEquals(this.modified_dtField, value) != true)) {
                    this.modified_dtField = value;
                    this.RaisePropertyChanged("modified_dt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsersHelper.PasswordActionType", Namespace="http://schemas.datacontract.org/2004/07/UsersLibrary")]
    public enum UsersHelperPasswordActionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Change = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reset = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="W2GOWCF.IUsersService")]
    public interface IUsersService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/GrantAccess", ReplyAction="http://tempuri.org/IUsersService/GrantAccessResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(where2go.W2GOWCF.AppException), Action="http://tempuri.org/IUsersService/GrantAccessAppExceptionFault", Name="AppException", Namespace="http://schemas.datacontract.org/2004/07/AppLibrary")]
        bool GrantAccess(string strUserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/GrantAccess", ReplyAction="http://tempuri.org/IUsersService/GrantAccessResponse")]
        System.Threading.Tasks.Task<bool> GrantAccessAsync(string strUserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/UsersAuth", ReplyAction="http://tempuri.org/IUsersService/UsersAuthResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(where2go.W2GOWCF.AppException), Action="http://tempuri.org/IUsersService/UsersAuthAppExceptionFault", Name="AppException", Namespace="http://schemas.datacontract.org/2004/07/AppLibrary")]
        where2go.W2GOWCF.UsersInfo[] UsersAuth(string strUserName, string strEmail, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/UsersAuth", ReplyAction="http://tempuri.org/IUsersService/UsersAuthResponse")]
        System.Threading.Tasks.Task<where2go.W2GOWCF.UsersInfo[]> UsersAuthAsync(string strUserName, string strEmail, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/CreateUsers", ReplyAction="http://tempuri.org/IUsersService/CreateUsersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(where2go.W2GOWCF.AppException), Action="http://tempuri.org/IUsersService/CreateUsersAppExceptionFault", Name="AppException", Namespace="http://schemas.datacontract.org/2004/07/AppLibrary")]
        where2go.W2GOWCF.UsersInfo[] CreateUsers(string strUserName, string strEmail, string strPassword, string strFirstName, string strLastName, int intCountry, string strMobile, string strImgUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/CreateUsers", ReplyAction="http://tempuri.org/IUsersService/CreateUsersResponse")]
        System.Threading.Tasks.Task<where2go.W2GOWCF.UsersInfo[]> CreateUsersAsync(string strUserName, string strEmail, string strPassword, string strFirstName, string strLastName, int intCountry, string strMobile, string strImgUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/ResendEmailUsers", ReplyAction="http://tempuri.org/IUsersService/ResendEmailUsersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(where2go.W2GOWCF.AppException), Action="http://tempuri.org/IUsersService/ResendEmailUsersAppExceptionFault", Name="AppException", Namespace="http://schemas.datacontract.org/2004/07/AppLibrary")]
        where2go.W2GOWCF.UsersInfo[] ResendEmailUsers(string strUserName, string strEmail, string strMobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/ResendEmailUsers", ReplyAction="http://tempuri.org/IUsersService/ResendEmailUsersResponse")]
        System.Threading.Tasks.Task<where2go.W2GOWCF.UsersInfo[]> ResendEmailUsersAsync(string strUserName, string strEmail, string strMobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/Password", ReplyAction="http://tempuri.org/IUsersService/PasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(where2go.W2GOWCF.AppException), Action="http://tempuri.org/IUsersService/PasswordAppExceptionFault", Name="AppException", Namespace="http://schemas.datacontract.org/2004/07/AppLibrary")]
        where2go.W2GOWCF.UsersInfo[] Password(string strUserName, string strEmail, string strMobile, where2go.W2GOWCF.UsersHelperPasswordActionType intKey, string strCurrentPassword, string strNewPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersService/Password", ReplyAction="http://tempuri.org/IUsersService/PasswordResponse")]
        System.Threading.Tasks.Task<where2go.W2GOWCF.UsersInfo[]> PasswordAsync(string strUserName, string strEmail, string strMobile, where2go.W2GOWCF.UsersHelperPasswordActionType intKey, string strCurrentPassword, string strNewPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsersServiceChannel : where2go.W2GOWCF.IUsersService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsersServiceClient : System.ServiceModel.ClientBase<where2go.W2GOWCF.IUsersService>, where2go.W2GOWCF.IUsersService {
        
        public UsersServiceClient() {
        }
        
        public UsersServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsersServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GrantAccess(string strUserName) {
            return base.Channel.GrantAccess(strUserName);
        }
        
        public System.Threading.Tasks.Task<bool> GrantAccessAsync(string strUserName) {
            return base.Channel.GrantAccessAsync(strUserName);
        }
        
        public where2go.W2GOWCF.UsersInfo[] UsersAuth(string strUserName, string strEmail, string strPassword) {
            return base.Channel.UsersAuth(strUserName, strEmail, strPassword);
        }
        
        public System.Threading.Tasks.Task<where2go.W2GOWCF.UsersInfo[]> UsersAuthAsync(string strUserName, string strEmail, string strPassword) {
            return base.Channel.UsersAuthAsync(strUserName, strEmail, strPassword);
        }
        
        public where2go.W2GOWCF.UsersInfo[] CreateUsers(string strUserName, string strEmail, string strPassword, string strFirstName, string strLastName, int intCountry, string strMobile, string strImgUrl) {
            return base.Channel.CreateUsers(strUserName, strEmail, strPassword, strFirstName, strLastName, intCountry, strMobile, strImgUrl);
        }
        
        public System.Threading.Tasks.Task<where2go.W2GOWCF.UsersInfo[]> CreateUsersAsync(string strUserName, string strEmail, string strPassword, string strFirstName, string strLastName, int intCountry, string strMobile, string strImgUrl) {
            return base.Channel.CreateUsersAsync(strUserName, strEmail, strPassword, strFirstName, strLastName, intCountry, strMobile, strImgUrl);
        }
        
        public where2go.W2GOWCF.UsersInfo[] ResendEmailUsers(string strUserName, string strEmail, string strMobile) {
            return base.Channel.ResendEmailUsers(strUserName, strEmail, strMobile);
        }
        
        public System.Threading.Tasks.Task<where2go.W2GOWCF.UsersInfo[]> ResendEmailUsersAsync(string strUserName, string strEmail, string strMobile) {
            return base.Channel.ResendEmailUsersAsync(strUserName, strEmail, strMobile);
        }
        
        public where2go.W2GOWCF.UsersInfo[] Password(string strUserName, string strEmail, string strMobile, where2go.W2GOWCF.UsersHelperPasswordActionType intKey, string strCurrentPassword, string strNewPassword) {
            return base.Channel.Password(strUserName, strEmail, strMobile, intKey, strCurrentPassword, strNewPassword);
        }
        
        public System.Threading.Tasks.Task<where2go.W2GOWCF.UsersInfo[]> PasswordAsync(string strUserName, string strEmail, string strMobile, where2go.W2GOWCF.UsersHelperPasswordActionType intKey, string strCurrentPassword, string strNewPassword) {
            return base.Channel.PasswordAsync(strUserName, strEmail, strMobile, intKey, strCurrentPassword, strNewPassword);
        }
    }
}
